'use client'

import { useState } from 'react'

interface CheckItem {
  id: string
  label: string
  detail: string
  category: string
  docsUrl?: string
}

const CHECKLIST: CheckItem[] = [
  // Naming
  { id: 'name-lowercase', label: 'Module name is all lowercase with underscores', detail: 'e.g. fastqc, samtools/sort, gatk4/haplotypecaller — tool name / subtool name', category: 'Naming', docsUrl: 'https://nf-co.re/docs/contributing/modules#naming-conventions' },
  { id: 'name-match', label: 'Directory name matches the process name in ALLCAPS', detail: 'modules/nf-core/fastqc/ → process FASTQC { ... }', category: 'Naming' },
  // Files
  { id: 'files-main', label: 'main.nf is present and follows the nf-core template', detail: 'Must have: tag, label, conda, container, input, output, when, script blocks', category: 'Required files', docsUrl: 'https://nf-co.re/docs/contributing/modules' },
  { id: 'files-meta', label: 'meta.yml is present and fully documented', detail: 'Must include: name, description, keywords, tools, input schema, output schema, authors', category: 'Required files' },
  { id: 'files-env', label: 'environment.yml uses exact pinned Bioconda version', detail: 'bioconda::tool=exact.version — never >= or > constraints', category: 'Required files' },
  { id: 'files-test', label: 'tests/main.nf.test is present', detail: 'At least one test() block. Run nf-test test before submitting.', category: 'Required files', docsUrl: 'https://www.nf-test.com/' },
  { id: 'files-snap', label: 'tests/main.nf.test.snap snapshot is committed', detail: 'Generated by the first test run — commit it to git so CI can compare', category: 'Required files' },
  // Module content
  { id: 'meta-map', label: 'Input/output follows [meta, file] tuple convention', detail: 'First element is always val(meta) — the Groovy Map carrying sample info', category: 'Module conventions' },
  { id: 'versions', label: 'versions.yml is emitted with exact tool version', detail: 'cat <<-END_VERSIONS > versions.yml must be in the script block', category: 'Module conventions', docsUrl: 'https://nf-co.re/docs/contributing/modules#software-versions' },
  { id: 'ext-args', label: 'Extra arguments use task.ext.args pattern', detail: 'def args = task.ext.args ?: \'\' — allows pipelines to add flags without editing the module', category: 'Module conventions' },
  { id: 'ext-prefix', label: 'Output prefix uses task.ext.prefix ?: "${meta.id}"', detail: 'Ensures output files are named by sample ID, not hard-coded strings', category: 'Module conventions' },
  // Container
  { id: 'container-both', label: 'Container block has both Singularity and Docker images', detail: 'Use the ternary workflow.containerEngine expression — always provide both', category: 'Container' },
  { id: 'container-pinned', label: 'Container image version matches environment.yml exactly', detail: 'biocontainers/fastqc:0.12.1--hdfd78af_0 must match bioconda::fastqc=0.12.1', category: 'Container' },
  // Tests
  { id: 'test-pass', label: 'nf-test tests pass locally', detail: 'Run: nf-test test modules/nf-core/your_module/tests/main.nf.test', category: 'Tests' },
  { id: 'test-testdata', label: 'Tests use nf-core/test-datasets files only', detail: 'Use params.modules_testdata_base_path — do not commit test data to nf-core/modules', category: 'Tests', docsUrl: 'https://nf-co.re/docs/contributing/test-data' },
  { id: 'test-edge', label: 'At least one edge case is tested (single-end, empty, etc.)', detail: 'e.g. test("Single-end reads") { ... } alongside the standard paired-end test', category: 'Tests' },
  // CI
  { id: 'ci-linting', label: 'nf-core modules lint passes without errors', detail: 'Run: nf-core modules lint your_module — fixes all errors before submitting', category: 'CI', docsUrl: 'https://nf-co.re/docs/nf-core-tools/cli/modules/lint' },
  { id: 'ci-prettier', label: 'Files are formatted with Prettier', detail: 'Run: prettier --write modules/nf-core/your_module/ — CI enforces formatting', category: 'CI' },
]

const CATEGORIES = [...new Set(CHECKLIST.map(c => c.category))]

export function PRChecklist() {
  const [checked, setChecked] = useState<Set<string>>(new Set())
  const [expandedItem, setExpandedItem] = useState<string | null>(null)

  const toggle = (id: string) => {
    setChecked(prev => {
      const next = new Set(prev)
      if (next.has(id)) next.delete(id); else next.add(id)
      return next
    })
  }

  const total = CHECKLIST.length
  const done  = checked.size
  const pct   = Math.round((done / total) * 100)

  return (
    <div className="flex flex-col gap-5">
      <div>
        <h3 className="text-base font-bold text-fg-primary mb-1">nf-core Module PR Checklist</h3>
        <p className="text-sm text-fg-secondary leading-relaxed">
          Every PR to <a href="https://github.com/nf-core/modules" target="_blank" rel="noopener noreferrer"
            className="text-teal-500 hover:text-teal-600">nf-core/modules</a> is reviewed against this checklist.
          Check each item to see if your module is ready for submission.
        </p>
      </div>

      {/* Progress bar */}
      <div className="flex flex-col gap-1.5">
        <div className="flex items-center justify-between text-xs text-fg-muted">
          <span>{done} / {total} items checked</span>
          <span style={{ color: done === total ? 'var(--color-success)' : 'var(--color-fg-muted)' }}>
            {done === total ? '✓ Ready to submit!' : `${pct}% complete`}
          </span>
        </div>
        <div className="w-full h-2 rounded-full" style={{ background: 'var(--color-border)' }}>
          <div
            className="h-2 rounded-full transition-all duration-normal ease-out-quart"
            style={{
              width: `${pct}%`,
              background: done === total ? 'var(--color-success)' : 'var(--color-teal-500)',
            }}
          />
        </div>
      </div>

      {/* Checklist by category */}
      <div className="flex flex-col gap-4">
        {CATEGORIES.map(cat => {
          const items = CHECKLIST.filter(c => c.category === cat)
          const catDone = items.filter(c => checked.has(c.id)).length
          return (
            <div key={cat}>
              <div className="flex items-center justify-between mb-2">
                <p className="text-xs font-bold text-fg-muted uppercase tracking-wide">{cat}</p>
                <span className="text-xs text-fg-muted">{catDone}/{items.length}</span>
              </div>
              <div className="flex flex-col gap-1">
                {items.map(item => (
                  <div key={item.id}>
                    <div
                      className="flex items-start gap-3 px-3 py-2 rounded-lg cursor-pointer hover:bg-surface-2 transition-colors"
                      onClick={() => toggle(item.id)}
                    >
                      <div
                        className="shrink-0 w-5 h-5 rounded border-2 flex items-center justify-center mt-0.5 transition-all"
                        style={{
                          borderColor: checked.has(item.id) ? 'var(--color-teal-500)' : 'var(--color-border)',
                          background: checked.has(item.id) ? 'var(--color-teal-500)' : 'transparent',
                        }}
                      >
                        {checked.has(item.id) && <span className="text-white text-xs">✓</span>}
                      </div>
                      <div className="flex-1 min-w-0">
                        <p className={`text-sm font-semibold leading-tight ${checked.has(item.id) ? 'line-through text-fg-muted' : 'text-fg-primary'}`}>
                          {item.label}
                        </p>
                        {expandedItem === item.id && (
                          <p className="text-xs text-fg-muted mt-1 leading-relaxed">{item.detail}</p>
                        )}
                      </div>
                      <button
                        onClick={e => { e.stopPropagation(); setExpandedItem(expandedItem === item.id ? null : item.id) }}
                        className="shrink-0 text-fg-muted hover:text-fg-secondary text-xs"
                      >
                        {expandedItem === item.id ? '▲' : '▼'}
                      </button>
                    </div>
                    {expandedItem === item.id && item.docsUrl && (
                      <div className="px-10 pb-2">
                        <a href={item.docsUrl} target="_blank" rel="noopener noreferrer"
                          className="text-xs text-teal-500 hover:text-teal-600">
                          docs ↗
                        </a>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )
        })}
      </div>

      <div className="flex gap-3 flex-wrap">
        <a href="https://nf-co.re/docs/contributing/modules" target="_blank" rel="noopener noreferrer"
          className="text-sm font-semibold text-teal-500 hover:text-teal-600">
          Full nf-core module contributing guide ↗
        </a>
        <a href="https://github.com/nf-core/modules/blob/master/.github/PULL_REQUEST_TEMPLATE/pull_request_template.md" target="_blank" rel="noopener noreferrer"
          className="text-sm font-semibold text-teal-500 hover:text-teal-600">
          Official PR template on GitHub ↗
        </a>
      </div>
    </div>
  )
}
